export const events = [
  { eventId: "333", eventName: "3x3x3" },
  { eventId: "222", eventName: "2x2x2" },
  { eventId: "444", eventName: "4x4x4" },
  { eventId: "555", eventName: "5x5x5" },
  { eventId: "666", eventName: "6x6x6" },
  { eventId: "777", eventName: "7x7x7" },
  { eventId: "333bf", eventName: "3x3x3 Blindfolded" },
  { eventId: "333fm", eventName: "3x3x3 Fewest Moves" },
  { eventId: "333oh", eventName: "3x3x3 One-Handed" },
  { eventId: "clock", eventName: "Clock" },
  { eventId: "minx", eventName: "Megaminx" },
  { eventId: "pyram", eventName: "Pyraminx" },
  { eventId: "skewb", eventName: "Skewb" },
  { eventId: "sq1", eventName: "Square-1" },
  { eventId: "444bf", eventName: "4x4x4 Blindfolded" },
  { eventId: "555bf", eventName: "5x5x5 Blindfolded" },
  { eventId: "333mbf", eventName: "3x3x3 Multi-Blind" },
];
