export const events = [
  { eventId: "333", eventName: "3x3x3" },
  { eventId: "222", eventName: "2x2x2" },
  { eventId: "444", eventName: "4x4x4" },
  { eventId: "555", eventName: "5x5x5" },
  { eventId: "666", eventName: "6x6x6" },
  { eventId: "777", eventName: "7x7x7" },
  { eventId: "333bf", eventName: "3x3x3 Blindfolded" },
  { eventId: "333fm", eventName: "3x3x3 Fewest Moves" },
  { eventId: "333oh", eventName: "3x3x3 One-Handed" },
  { eventId: "clock", eventName: "Clock" },
  { eventId: "minx", eventName: "Megaminx" },
  { eventId: "pyram", eventName: "Pyraminx" },
  { eventId: "skewb", eventName: "Skewb" },
  { eventId: "sq1", eventName: "Square-1" },
  { eventId: "444bf", eventName: "4x4x4 Blindfolded" },
  { eventId: "555bf", eventName: "5x5x5 Blindfolded" },
  { eventId: "333mbf", eventName: "3x3x3 Multi-Blind" },
];

export const states = [
  { name: "Andhra Pradesh", id: "AP" },
  { name: "Arunachal Pradesh", id: "AR" },
  { name: "Assam", id: "AS" },
  { name: "Bihar", id: "BR" },
  { name: "Chhattisgarh", id: "CT" },
  { name: "Goa", id: "GA" },
  { name: "Gujarat", id: "GJ" },
  { name: "Haryana", id: "HR" },
  { name: "Himachal Pradesh", id: "HP" },
  { name: "Jharkhand", id: "JH" },
  { name: "Karnataka", id: "KA" },
  { name: "Kerala", id: "KL" },
  { name: "Madhya Pradesh", id: "MP" },
  { name: "Maharashtra", id: "MH" },
  { name: "Manipur", id: "MN" },
  { name: "Meghalaya", id: "ML" },
  { name: "Mizoram", id: "MZ" },
  { name: "Nagaland", id: "NL" },
  { name: "Odisha", id: "OR" },
  { name: "Punjab", id: "PB" },
  { name: "Rajasthan", id: "RJ" },
  { name: "Sikkim", id: "SK" },
  { name: "Tamil Nadu", id: "TN" },
  { name: "Telangana", id: "TG" },
  { name: "Tripura", id: "TR" },
  { name: "Uttar Pradesh", id: "UP" },
  { name: "Uttarakhand", id: "UT" },
  { name: "West Bengal", id: "WB" },
];
